### ISSUE TITLE
An option to redirect fflive output to file or stdout

### ISSUE THREAD

**Issue by pawelzwronek** [ramiropolla/ffglitch-core#3]
Hi @ramiropolla
I'm working on a simple gui app in tkinter for ffglitch, it's called LiveMosher. I would like to add an option to record output of fflive to file but fflive(ffplay) has no such option. Would it be possible that you add an option to stream raw moshed input stream to file or stdout with option `-o file.raw` or `-o -` ? And of course thanks for such great piece of software 👏

**Comment by ramiropolla** [comment]
Hi @pawelzwronek,

In the `setup()` function, you can set the output path in `args.output`. This works both for `ffedit` and `fflive`. I usually add a date string to the output file so that different runs don't overwrite each other:
```js
  // get input filename
  const input_fname = args.input;

  // create a new output filename based on the current time
  // and the input filename
  const date_str = new Date().toISOString().replaceAll(':', '_');
  const output_fname = `glitched_${date_str}_${input_fname}`;
  args.output = output_fname;
  console.log(`Output filename is "${output_fname}"`);
```

More information about `setup()` here: https://ffglitch.org/docs/0.10.1/ffedit/#transplicate-with-script

I'll try to update the `fflive` documentation to make this information easier to find.

**Comment by pawelzwronek** [comment]
Oh cool and thanks for fast replay. I assumed that if -o is not working, then args.output would not too, but was to lazy to test it ;)

**Comment by pawelzwronek** [comment]
Sorry for asking again, but the feature of `-o file.raw` and `-o -` would really ease my life much. Now to output I need to inject `args.output = "out.raw";` into a copy of selected script to avoid editing an original file, then copy it to temp folder. It was working well for simple script but when the script import another script it's not working well. Also lines numbers from quickjs output console are wrong, script filename too. I would be very grateful if you would add this option and publish the binaries for Windows.

My app is this state right now:
![obraz](https://github.com/user-attachments/assets/f48017a9-3b01-4c83-a4e6-49a3c38a2744)

**Comment by ramiropolla** [comment]
Can you tell me the entire command line you're using, and any modifications you are doing to the scripts?
You can also use `-sp <parameter>` to get a parameter from the command line into `setup()`. Perhaps you could use that instead?

**Comment by pawelzwronek** [comment]
`ffgac -i any.mp4 -vcodec mpeg4 -f rawvideo -` ->(with python pipe) to `fflive -i - -s script.js -sp param1`
To use sp parameters I need to edit source script and I would like to avoid it, to make recording to file as transparent to user as possible. When you select any script file a fflive window is shown with live preview.

**Comment by ramiropolla** [comment]
For some reason I had thought the `-o` option was already taken by `ffplay`, but it turned to be free, so it was quite an easy fix: https://github.com/ramiropolla/ffglitch-core/commit/2d3c781a9ce1a6be1c807f2af2231bdf6dbe04be.

I don't know when I'll release a new build though.

**Comment by pawelzwronek** [comment]
Name of the option is not important, it can be anything. Do you think enabling it in mentioned commit is enough or more changes are needed?

**Comment by pawelzwronek** [comment]
Just want to tell you I've started working to add this feature. Already managed to build binaries for linux. Expect a PR soon :)

**Comment by ramiropolla** [comment]
By the way, I just added github actions to make builds for all supported platforms. That might help you create your own custom builds if you need to make a release before your PRs get merged.

**Comment by pawelzwronek** [comment]
Cool but I managed yesterday to build it for all 3 platforms. Building cross platform was challenging and ended building on target platform. Need to see how you did it.
